<script lang="ts">
  import axios from "axios";
  import { onMount } from "svelte";
  import {
    ChevronLeft,
    ChevronRight,
    ChevronsLeft,
    ChevronsRight,
    FileQuestionIcon,
    UserCog,
    TouchpadOffIcon,
    Search,
    ShieldAlert,
    SignalLow,
    SignalMedium,
    SignalHigh,
    Signal,
  } from "@lucide/svelte";
  import type { Alert } from "$src/lib/components/alerts/columns";
  import { toast } from "svelte-sonner";
  import * as Table from "$lib/components/ui/table/index.js";
  import { sendError } from "$src/lib/utils";
  import * as Select from "$lib/components/ui/select/index.js";
  import * as DropdownMenu from "$lib/components/ui/dropdown-menu/index.js";
  import { navigate } from "sv-router/generated";
  import type { Client } from "$src/lib/stores/client";
  import Input from "$src/lib/components/ui/input/input.svelte";
  import Filters from "$src/lib/components/alerts/filters.svelte";
  import Button from "$src/lib/components/ui/button/button.svelte";
  import FiltersSingle from "$src/lib/components/alerts/filtersSingle.svelte";

  // ALERTS

  let clients = $state<Client[] | null>(null);

  function loadClients() {
    axios
      .get("/api/clients")
      .then((response) => {
        clients = response.data.clients;
      })
      .catch((error) => {
        sendError("Error fetching clients:", error);
      });
  }

  function getClient(clientId: string): Client {
    if (!clients) {
      return { Name: "Loading...", ID: clientId } as Client;
    }
    const client = clients.find((c) => c.ID === clientId);
    if (!client) {
      return { Name: "Unknown Client", ID: clientId } as Client;
    }
    return client;
  }

  // ALERTS

  interface AlertWithOpen extends Alert {
    Open: boolean;
  }

  let shownAlerts = $state<AlertWithOpen[] | null>(null);
  let currentPage = $state(1);
  let maxPage = $state(1);
  let perPage = $state("20");
  let searchFilter = $state("");
  let severityFilter = $state<string[]>([]);
  let clientFilter = $state<string>("");

  function loadAlerts() {
    shownAlerts = null;
    axios
      .get("/api/alerts", {
        params: {
          page: currentPage,
          perPage: perPage,
          severity: severityFilter.join(","),
          search: searchFilter,
          client: clientFilter,
        },
      })
      .then((res) => {
        console.log(res.data.alerts);
        shownAlerts = res.data.alerts.map((alert: Alert) => ({
          ...alert,
          Open: false, // Initialize dropdown state to closed
        })) as AlertWithOpen[];
        maxPage = res.data.maxPage;
      })
      .catch((err) => {
        toast.error("Internal server error");
        console.error("Error fetching alerts", err);
      });
  }

  // SEVERITY

  export const severity = [
    {
      value: "low",
      label: "Low",
      icon: SignalLow,
    },
    {
      value: "medium",
      label: "Medium",
      icon: SignalMedium,
    },
    {
      value: "high",
      label: "High",
      icon: SignalHigh,
    },
    {
      value: "critical",
      label: "Critical",
      icon: Signal,
    },
  ];

  onMount(() => {
    loadAlerts();
    loadClients();
  });
</script>

<div class="flex justify-between flex-wrap gap-8 items-center">
  <div>
    <h1 class="flex items-center gap-4">
      <ShieldAlert/>
      Alerts
    </h1>

    <p class="mb-4 text-muted-foreground">
      View and manage alerts generated by Wazuh and the Indexer.
    </p>
  </div>
</div>

<div class="my-10 flex gap-2 flex-wrap w-full">
  <Input
    bind:value={searchFilter}
    placeholder="Filter tasks..."
    class="h-8 w-[150px] lg:w-[250px]"
  />
  <Filters
    title="Severity"
    options={severity}
    bind:selectedValues={severityFilter}
  />
  <FiltersSingle
    title="Client"
    options={clients?.map((client) => ({
      value: client.ID,
      label: client.Name,
      icon: UserCog,
    })) || []}
    bind:selectedValue={clientFilter}
  />
  <!-- Rule ID // maybe in search -->
  <!-- Time // maybe in search -->
  <Button
    variant="ghost"
    onclick={() => {
      loadAlerts();
      currentPage = 1;
    }}
    ><Search />
  </Button>
</div>

<Table.Root>
  <Table.Header>
    <Table.Row>
      <Table.Head>client</Table.Head>
      <Table.Head>severity</Table.Head>
      <Table.Head>title</Table.Head>
      <Table.Head>timestamp</Table.Head>
    </Table.Row>
  </Table.Header>
  <Table.Body>
    {#if shownAlerts === null}
      <Table.Row>
        <Table.Cell
          colspan={100}
          class="text-center animate-pulse text-muted-foreground"
        >
          Loading alerts...
        </Table.Cell>
      </Table.Row>
    {:else if shownAlerts.length === 0}
      <Table.Row>
        <Table.Cell colspan={100} class="text-center text-muted-foreground"
          >No alerts found.</Table.Cell
        >
      </Table.Row>
    {:else}
      {#each shownAlerts as alert (alert.ID)}
        <Table.Row>
          <Table.Cell class="flex gap-2 items-center">
            <a href={`/dashboard/clients/${alert.ClientID}`}>
              {getClient(alert.ClientID)?.Name}
            </a>
          </Table.Cell>
          <Table.Cell>
            {alert.RuleLevel}
          </Table.Cell>
          <Table.Cell class="whitespace-pre-wrap">
            <a href={`/dashboard/alerts/${alert.ID}`}>
              {alert.RuleDescription}</a
            ></Table.Cell
          >
          <Table.Cell>
            {alert.Timestamp}</Table.Cell
          >

          <Table.Cell>
            <DropdownMenu.Root bind:open={alert.Open}>
              <DropdownMenu.Trigger>...</DropdownMenu.Trigger>
              <DropdownMenu.Content>
                <DropdownMenu.Group>
                  <DropdownMenu.Label>{alert.ID}</DropdownMenu.Label>
                  <DropdownMenu.Separator />
                  <DropdownMenu.Item
                    onclick={() => navigate(`/dashboard/alerts/${alert.ID}`)}
                    >Details</DropdownMenu.Item
                  >
                </DropdownMenu.Group>
              </DropdownMenu.Content>
            </DropdownMenu.Root>
          </Table.Cell>
        </Table.Row>
      {/each}
    {/if}
  </Table.Body>
</Table.Root>

<div class="flex justify-between gap-4 flex-wrap items-center my-4">
  <div class="flex items-center gap-4">
    <p class="text-xs text-muted-foreground">
      Page {currentPage} of {maxPage} | Per page:
    </p>
    <Select.Root
      type="single"
      bind:value={perPage}
      onValueChange={() => {
        loadAlerts();
      }}
    >
      <Select.Trigger class="w-[80px] p-1 h-6">{perPage}</Select.Trigger>
      <Select.Content>
        <Select.Item value="10">10</Select.Item>
        <Select.Item value="20">20</Select.Item>
        <Select.Item value="50">50</Select.Item>
        <Select.Item value="100">100</Select.Item>
      </Select.Content>
    </Select.Root>
  </div>
  <div>
    <Button
      variant="ghost"
      disabled={currentPage === 1}
      onclick={() => {
        currentPage = 1;
        loadAlerts();
      }}
    >
      <ChevronsLeft />
    </Button>
    <Button
      variant="ghost"
      disabled={currentPage === 1}
      onclick={() => {
        currentPage -= 1;
        loadAlerts();
      }}
    >
      <ChevronLeft />
    </Button>

    <Button
      variant="ghost"
      disabled={currentPage === maxPage}
      onclick={() => {
        currentPage += 1;
        loadAlerts();
      }}
    >
      <ChevronRight />
    </Button>

    <Button
      variant="ghost"
      disabled={currentPage === maxPage}
      onclick={() => {
        currentPage = maxPage;
        loadAlerts();
      }}
    >
      <ChevronsRight />
    </Button>
  </div>
</div>
